### ISSUE TITLE
not working with newest version

### ISSUE THREAD

**Issue by andekande** [aervans/videojs-seek#1]
Reason is line 11:
if seekValue and @Ca in tech

There is no more a Ca property. It seems to get generated by minification for videojs releases.
What at all is the purpose of looking into tech variable?

**Comment by aervans** [comment]
The original reasoning for including the tech check escapes me at the moment. Regardless, relying on a reference to a minified variable is obviously very bad so I've removed it. I've retested in the newest version of Videojs and everything appears to be working as intended.

**Comment by andekande** [comment]
OK, works now.
Sidenote: there should be a more obvious way added to the readme on how to set up the plugin. You state: "automatically registers itself"
But that's confusing, because one has to include the call to seek, like so:

``` javascript
var vjs = videojs('id');
vjs.seek();
```

or as already explained

``` javascript
videojs('id', {}, function() {
  this.seek();
});
```

**Comment by aervans** [comment]
You're right. I've clarified the readme in 04a10f5ae1496124ecc2fd9d1a210159e0dc9c2b.
