### ISSUE TITLE
will not week on any browser

### ISSUE THREAD

**Issue by jjgallow** [aervans/videojs-seek#2]
Hello, my code, pasted below, worked (if I remember correctly) last year, and will not work now in any browser.  Are there any good examples of videojs-seek on the web ?   Or any suggestions why this code doesn't seek?

Thanks so much:

 <script src="video.js" type="text/javascript" charset="utf-8"></script>

<script src="videojs-seek.js" type="text/javascript" charset="utf-8"></script>

  <script src="final_js.js"  type="text/javascript" charset="utf-8">  </script>

  
  <link rel="stylesheet" href="video-js.css" type="text/css" media="screen" title="Video JS" charset="utf-8">
</head>
<body>

  <div class="video-js-box">
    
<video id="watertube" class="video-js vjs-default-skin vjs-big-play-centered" width="1056" height="720" controls autoplay preload="auto" poster="wslogo.jpg" data-setup='{ "playbackRates": [1, 1.5, 2,3,5,10] }'>   

 <source src="D4425.mp4" type='video/mp4' />

```
</video>
```

<script  type="text/javascript" charset="utf-8">

videojs('watertube').ready(function() {
  this.seek({  });
});
</script>

```
<!-- Download links provided for devices that can't play video in the browser. -->
</div>
```

**Comment by aervans** [comment]
@jjgallow, Apologies for the delay in responding. I have a few things on my plate at the moment but I'll check this out and get back to you in the next day or two!

**Comment by jjgallow** [comment]
No worries Adam, it turned out to just be a corrupt javascript file.  Thank
you for the great tool!

**Comment by aervans** [comment]
Awesome! Glad to hear you were able to resolve the issue.
